### ISSUE TITLE
Add Optimism (and other chains) to the registration frontend and the indexer

### ISSUE THREAD

**Issue by thelastjosh** [metagov/daostar#104]
This will require checking factory contracts, deploying a couple of OP testnet, etc. and is critical to supporting the OP tasks. @crazyyuan @Rashmi-278 please fill in additional plans & requirements here, and meet to discuss at some point this coming week / ASAP.

**Comment by crazyyuan** [comment]
The contracts are all deployed on goerli-optimism .
[EIP4824Index](https://goerli-optimism.etherscan.io/address/0x9aff4e5e7a7ae449b89162ef4798b2bb60dc92c0)
[EIP4824RegistrationSummoner](0x45E81552DEC1F57c18E3cbd69549252624b96D98)

And then, we need to create TheGraph indexer for this network.

**Comment by thelastjosh** [comment]
In the interests of keeping these indexers on DAOstar's own institutional servers, I just added Kahn and Mike to the Metagov Digital Ocean account, when they will deploy an indexer on a new droplet.

**Comment by Rashmi-278** [comment]
TheGraph Indexer has been deployed on the optimism-goerli network
------------------------------------------------------------------------------------------------------------------------
Build completed: QmNPd6AZ3dh2AMoiEf9384cSVRk3ztTfSU53cTRLgU7B7d

Deployed to https://thegraph.com/explorer/subgraph/rashmi-278/daostar-optimism-goerli

Subgraph endpoints:
Queries (HTTP):     https://api.thegraph.com/subgraphs/name/rashmi-278/daostar-optimism-goerli
Subscriptions (WS): wss://api.thegraph.com/subgraphs/name/rashmi-278/daostar-optimism-goerli

**Comment by Rashmi-278** [comment]
PR for the optimism-goerli is created https://github.com/metagov/daostar/pull/111

> The contracts are all deployed on goerli-optimism . [EIP4824Index](https://goerli-optimism.etherscan.io/address/0x9aff4e5e7a7ae449b89162ef4798b2bb60dc92c0) [EIP4824RegistrationSummoner](0x45E81552DEC1F57c18E3cbd69549252624b96D98)
> 
> And then, we need to create TheGraph indexer for this network.

**Comment by crazyyuan** [comment]
Register DAO succeed.
https://goerli-optimism.etherscan.io/tx/0xdad55b57728b0011ef8f0f333be3b3bb0e364b2b15151fa461fe7cf88e11bea4

Optimism Goerli Indexer work fine.
https://thegraph.com/hosted-service/subgraph/rashmi-278/daostar-optimism-goerli

**Comment by thelastjosh** [comment]
I don't see the DAO on the explorer frontend though?

**Comment by Rashmi-278** [comment]
I looked into this, DAO is registered but for some reason, the DAO Name and other fields weren't saved and that's why it's not showing up on the explorer

![image](https://github.com/metagov/daostar/assets/41290852/5b997b72-3751-4571-9d19-8fc54830f62b)

Fixing this

**Comment by thelastjosh** [comment]
Rashmi submitted the PR, but it has not been merged yet. Kahn and Rashmi should all be able to merge the PR.

**Comment by Rashmi-278** [comment]
We successfully deployed a test DAO called Orchid DAO on optimism-goerli. 
Related PRs have been merged and this feature is live on production!
![image](https://github.com/metagov/daostar/assets/41290852/fdde5f1f-edbc-4f4a-a6f9-f60fd8684058)
![image](https://github.com/metagov/daostar/assets/41290852/6dce9d97-21c0-46c1-ae91-09372c788639)
![image](https://github.com/metagov/daostar/assets/41290852/2a8afa07-e04f-4efa-b268-cb47d0f6d8d2)
