### ISSUE TITLE
Wrapping up ONTOCHAIN for demo

### ISSUE THREAD

**Issue by thelastjosh** [metagov/daostar#105]
Josh needs
1. RASHMI: issuerURI for REPUTABLE, and in the memberAttestationsURI field, putting the DAOIP-3-compatible that's serving the actual data for REPUTABLE
2. MENDES: create a attestationIssuerURI for MetagovDAO, please send to Josh so he can handle updating the daoURI for MetagovDAO
3. MENDES: issuerURI for Govrn, and in the memberAttestationsURI field, putting the DAOIP-3-compatible endpoint that's serving the actual data for Govrn
4. JOSH: change metagovDAO's daoURI
5. RASHMI: Improvement to the frontend for the daostar.org explorer, to make sure that the explorer is returning the "attestationIssuerURI" field in the appropriate place in the explorer

Additional discussion elements to address later: 
- [Are we making the wrong assumption here? In this sense, the DAO is declaring trust to a set of service providers. BUT is that the wrong assumption? Instead of DAOs themselves declaring "these are trustworthy nodes", you could... (1) have just a well-known node in this network declaring things are trustworthy, e.g. DAOstar itself, (2)  ...]
- [This shouldn't be about "trust", just think of it as a gossip network, not guarantees on reliability.]

**Comment by Rashmi-278** [comment]
All tasks from 1-5 were completed and delivered
