### ISSUE TITLE
Update EIP-4824, finalize, ping the EIP editors

### ISSUE THREAD

**Issue by thelastjosh** [metagov/daostar#109]
List of things to edit into the EIP:

- [x] add 'orgURI' and 'entityURI' as aliases
- [x] name
- [x] proposalsURI
- [x] activityLogURI
- [x] context
- [x] add advice: if you don't have any value for a field (e.g. for "description"), just don't include the field, don't leave it blank ""
- [x] change http in context to https
- [x] Typo under Members, “membersuRI”
- [x] Clarify that you can replace “membersURI” with just “members” if you want to in all DAOstar schemas. Similarly with “proposalsURI” and “proposals”.
    - [x] Or is this bad practice? What if someone tries to report a JSON with BOTH membersURI and members; how do you parse that? I guess, always look for membersURI first, and then for members?
- [x] Revise contractsURI to make clear that contracts pointed at the same daoURI can cite each other. Also, implement + describe an id for contracts, “CAIP-10 address + “?contractId=“ + CONTRACT_COUNTER”.
- [x] Look up what’s best practice: either remove “type: DAO”, etc. extra “contextual” fields from the array lists for proposals, members, etc. or add them all into the new standards.
- [x] Remove the double copy of “activities” under ActivityLog [or just remove ActivityLog altogether?]
- [x] Contracts JSON not being recognized as JSON
- [x] Consider changing member format from type, id to id: {type, value} (decided against doing this, after doing more research into how VC approaches this---effectively the value should be a URI, not another JSON object. Though I'm not 100% on this since I vaguely remember that someone somewhere had taken the nested approach).
- [x] "name". Based on conversation with Fabien. Consider removing "name" from all the sub JSON files. this way, if anyone changes the name, you do not need to change all these files, which is problematic.
- [x] consider changing "type" in the member list so it's not just "EthereumAddress" but something more useful and informative, like "Member", "Administrator", "Moderator", and so on. "type": "EthereumAddress" feels strange, though it's hard to know how to resist. If it's Arbitrum, should I put ArbitrumAddress? - If it's another chain, should I use eip155, etc. If it's EVM-type address, should. If it was me, I would say "type: Administrator, Moderator, etc. etc.". It would be nice to have a schema for ROLES. I like the approach of Safe with this, you put the treasury that the DAO defines (and you can add multiple treasuries, on multiple chains), also has a short name.

# DAO ID.
- [x] Decide whether this needs to exist in 4824. Probably not.
- [ ] Add an “id” for DAOs.
    - [ ] Do DAOs need “ids”? What about the loose, amorphous vision of a DAO, composed of many loosely-affiliated parts? Can you assign an “id” to that? Nonetheless, many DAOs DO effectively have unique IDs, i.e. their main governance contract. Insofar as all the loosely-affiliated parts can agree on a daoURI, the daoURI effectively becomes an id. But if you take this emergent definition / want people to treat daoURI itself as the ID, then any random thing could point their daoURI at a DAO’s daoURI, and “be part of the DAO”. That doesn’t work!
    - [ ] No, DAO ID SHOULD probably just be the CAIP-10 address of the main governance contract, or really of ANY smart contract in the DAO’s contract space—so long as they all agree. Insofar as there are multiple governance contracts, as long as they cite the same daoURI, and contractsURI includes all those contracts, then it should be good. You know they “belong” together.
    - [ ] Can the DAO ID change? What if they upgrade the main governance contract? Do they then HAVE to change the id? Would that fuck a lot of things up?
        - [ ] Should we expect DAO ID to be permanent?

## Notes from conversations with Snapshot
A daoID field?
* right now, "name" is kind of the ID field, but that's not very sufficient. Many of these DAOs have multiple voting spaces, but there isn't one thing that links them in the standard. 
* we need a decentralized registry system for DAO IDs, probably based on eip155, but something extensible and includes management functions. Maybe a use-case for ENS?
* Snapshot is ENS-integrated. If we could go back, we would have generated an internal ID on our side, and then resolve the ENS to that ID. This is what we do on SnapshotX, for example. Because some people change their ENS name, some want multiple ENS domains, some want another registry system. Being able to resolve on our UI makes it's much easier to do all this. Right now we store everything as an ENS domain but we know this may change over time. If it's "an internal ID" it would just resolve on the UI. It would just link the DAO to the ENS domain. 

GovernanceURI
* snapshot does not have a good value for that. Maybe: I could auto-generate some text around the voting pool and voting strategies. Maybe I could auto-generate some information.
* IDEA: this suggests modular descriptions for governance specification? Would need a new standard

"proposalsURI"
- contentURI to be the actual content of the proposal, i.e. the text
- ADD discussionsURI to be the link-to discussions, e.g. a Discourse link, twitter thread, etc.
- change text to clarify 
- the call value for SnapshotX: https://snapshot.4everland.link/ipfs/QmW1Bvvpzzz3ahq4TKLknBnVb5RG3KdEJUUxoQXptC8NzE

We should have a demo for this! Here's what you can do with that standard.

Member:
- Roles in Snapshot: Controller, Administrator. A space may define a certain strategy, but the author can always bypass this.
- (What he's calling for is a kind of "meta-identity layer")
- "type": "EthereumAddress" feels strange. If it's Arbitrum, should I put ArbitrumAddress? - If it's another chain, should I use eip155, etc. If it's EVM-type address, should. If it was me, I would say "type: Administrator, Moderator, etc. etc.". It would be nice to have a schema for ROLES. I like the approach of Safe with this, you put the treasury that the DAO defines (and you can add multiple treasuries, on multiple chains), also has a short name.

activityLogURI
- On snapshot, we store all the activity: when you join/follow, when you vote, etc. etc.
- We can filter that by space, but we cannot filter that by proposal. We could show the vote by proposal, but it's a bit more deep integration.
- Right now, you're exporting the follow/join, propose, delegate, flag proposal, subscribe, vote actions FOR THE SPACE.
- We could imagine someone integrating subscribe for the proposal, but that's not currently set up.
- JOSH: stage some well-defined activity types, for example a vote on a proposal. it would be nice to list all the possible types

**Comment by thelastjosh** [comment]
Josh made some progress on updating the EIP
1. getting rid of reference implementations from main text, porting that to a new folder
2. updating some of hte language
3. will send this PR hopefully later today

**Comment by eleventh19** [comment]
Need to double check the edits and whether the outreach to editors has taken place - @thelastjosh can you please provide an update

**Comment by thelastjosh** [comment]
Closing this issue as I've just sent out the PR to Ethereum https://github.com/ethereum/ERCs/pull/330
Will copy over to DAOIP-2 in our repo once that merges.
Moving over all the DAO id discussions and notes to a new issue.

**Comment by thelastjosh** [comment]
Just a note that this is FINALLY merged. See https://github.com/ethereum/ERCs/pull/330
