### ISSUE TITLE
Devconnect Istanbul in November - what is DAOstar doing?

### ISSUE THREAD

**Issue by thelastjosh** [metagov/daostar#110]
November 13 - 19
Two-week Zuzalu gathering also in Istanbul right before

What could we do?
- public goods conference? (Eugene)
- Kaitlin from Filecoin— a Filecoin+Metagov dinner?
- other things?

Post suggestions below! 

Definitely going
- Eugene
- Rashmi
- maybe Aman
- maybe Josh
- maybe Ammar Hasan from Metagov? check

**Comment by amanwithwings** [comment]
Closing this issue for obvious reasons.
