### ISSUE TITLE
Review PlanckerDAO Nouns framework + proposal

### ISSUE THREAD

**Issue by unfriendlyamendment** [metagov/daostar#125]
Plancker has completed the technical standard for Nouns and drafted a proposal for adoption (proposal pending review and edit)

TO REVIEW: technical standard -- @thelastjosh to review? 
https://github.com/metagov/daostar/tree/312c5b7ad3b4f2842d3482a9c0cca87912cb0ffd/Implementations/Nouns

TO Review: Nouns Proposal Draft -- @amanwithwings to review? 
https://hackmd.io/@link/HygVEzoU2/edit

**Comment by amanwithwings** [comment]
@unfriendlyamendment , the proposal needs to be read more finely and edited. It carries over many details from its original version (the same proposal to ENS), including addresses, working group names, etc. These details need to be changed to what they are for Nouns.

**Comment by Rashmi-278** [comment]
@amanwithwings Please update the registration summoner contract address used in this proposal.
It should be https://etherscan.io/address/0x2dac5dbbf1d024c1e0d9c92d3aeda7618e15add7

Reference : https://github.com/metagov/daostar#ethereum

**Comment by Rashmi-278** [comment]
I think it would also be helpful if we included the call data too

**Comment by amanwithwings** [comment]
Any progress here @unfriendlyamendment? Would be great if we could check in on PlanckerDAO to see if they need any support on this.

**Comment by unfriendlyamendment** [comment]
@amanwithwings no progress thus far, I will touch base with the plancker team.
