### ISSUE TITLE
[Bug] Manager address not showing on explorer

### ISSUE THREAD

**Issue by thelastjosh** [metagov/daostar#126]
Why is it not working, how can we fix it?

**Comment by thelastjosh** [comment]
Noting that there is some limited feedback from DAOs indicating this is an important feature that should work! (Plus it's obviously part of the standard as well)

**Comment by Rashmi-278** [comment]
One should be able to deploy a registration with a daoURI, with or without a manager address

**Comment by Rashmi-278** [comment]
WIP PR: 
https://github.com/metagov/daostar/pull/132

**Comment by thelastjosh** [comment]
Just noting that not all indexed DAOs with daoURI will have a manager address (e.g. those that just put daoURI directly into their contracts) because they have other governance.

**Comment by Rashmi-278** [comment]
Will be done by EOD, Need to update DAO URI for this, there is a manager address field missing

**Comment by thelastjosh** [comment]
Any update on this?

**Comment by Rashmi-278** [comment]
The PR has been ready for while https://github.com/metagov/daostar/pull/135 , but there are some blockers 
I'm unable to deploy the new changes to DAOstar API
**Blockers**
- DAO* API deployed on Digital Ocean Droplet needs to be reloaded to reflect the changes
- After the above step, we need to deploy the graph instances for all the networks once again

**Comment by Rashmi-278** [comment]
Resolved. Demo: https://daostar.org/registration/optimismGoerli:0xb76f34f3b1736bcf336e32a9c36d319aabf926e1

![image](https://github.com/metagov/daostar/assets/41290852/770f7422-1575-47d1-b8b8-f0c5d39c51c2)

Note: Manager Address here is being retrieved from DAO URI and not the EIP 4824 smart contract, we need to update our smart contracts to included it as an event parameter
