### ISSUE TITLE
[Bug] Contract Address for a new registration is being saved incorrectly

### ISSUE THREAD

**Issue by Rashmi-278** [metagov/daostar#130]
Registration  contract addresses for Lyra - Demo and ENS DAO were lyra.eth and ens.eth
but my wallet address ( I registered them ) was saved as contract address.

![image](https://github.com/metagov/daostar/assets/41290852/cd6f9456-7422-47b0-920f-c4c777aaad25)

**Comment by amanwithwings** [comment]
@Rashmi-278 , perhaps you can also recheck this as a part of this issue: 

When I try to generate a daoURI using the snapshot integration, it doesn't include the _manager address_ or a _contracts registry URI_. Are these being stored anywhere given that the form is accepting them?

**Comment by Rashmi-278** [comment]
Hey Aman, I checked the reason for this, we don't have those fields included in the DAO URI Validation schema in our API
![image](https://github.com/metagov/daostar/assets/41290852/685d374e-6c47-4879-82dc-12bfe664b633)

**Comment by Rashmi-278** [comment]
> @Rashmi-278 , perhaps you can also recheck this as a part of this issue:
> 
> When I try to generate a daoURI using the snapshot integration, it doesn't include the _manager address_ or a _contracts registry URI_. Are these being stored anywhere given that the form is accepting them?

This is a new issue, https://github.com/metagov/daostar/issues/134

**Comment by thelastjosh** [comment]
First field in registration interface should be hidden because it's not actually used to populate the explorer / daoURI; the contract address is the actual contract address that calls summonRegistration. 

However, a contract address is still sometimes useful for populating other endpoints, e.g. for Snapshot. This requirement / change in the interface should get rolled into the new consolidated spec.

**Comment by eleventh19** [comment]
Have listed all three bugs in a consolidated spec, meeting getting scheduled for the week of Sept 18 once Rashmi and Josh are back from conference travel

**Comment by thelastjosh** [comment]
Rashmi will add a PR to hide it and close it.

**Comment by Rashmi-278** [comment]
PR is ready to be merged https://github.com/metagov/daostar/pull/154

**Comment by Rashmi-278** [comment]
PR merged, closing this issue
