### ISSUE TITLE
Draft architecture document of backend service

### ISSUE THREAD

**Issue by crazyyuan** [metagov/daostar#131]
Existing:
1. DAOstar website backend service.
2. DAO URI backend service.

Upcoming:
1. ERC-4824 data cache service. (For DAO voters integrate with Snapshot)

**Comment by crazyyuan** [comment]
This is a draft document:
https://docs.google.com/document/d/1u0nFI3oQuZN9lzbCDsziFj3-ElkkGtBJQRkIarLtvz8/edit

**Comment by crazyyuan** [comment]
related issues:
1. https://github.com/metagov/daostar/issues/88#issuecomment-1686663188
2. https://github.com/metagov/daostar/issues/127#issue-1863403790

**Comment by thelastjosh** [comment]
@Rashmi-278 if you could add the link above to the frontend design doc it would be useful reference material, so that the frontend and backend are evolving together.

**Comment by Rashmi-278** [comment]
> @Rashmi-278 if you could add the link above to the frontend design doc it would be useful reference material, so that the frontend and backend are evolving together.

Done, I've added it.

**Comment by Rashmi-278** [comment]
> @Rashmi-278 if you could add the link above to the frontend design doc it would be useful reference material, so that the frontend and backend are evolving together.

Done, I've added it.
