### ISSUE TITLE
Support Optimism main network

### ISSUE THREAD

**Issue by crazyyuan** [metagov/daostar#139]
1. Deploy all contracts on Optimism.
2. Create TheGraph for Optimism.
3. Add Optimism select on the frontend.
4. Document these.

**Comment by crazyyuan** [comment]
TheGraph Indexer has been deployed on the Optimism network
https://thegraph.com/hosted-service/subgraph/crazyyuan/daostar-optimism

PR for these: https://github.com/metagov/daostar/pull/141

**Comment by Rashmi-278** [comment]
PR for frontend: https://github.com/metagov/daostar/pull/145

**Comment by Rashmi-278** [comment]
Documentation: https://hackmd.io/@torchablazed/Byjs0UQ0n

**Comment by Rashmi-278** [comment]
We are live with OP Mainnet support !
 
![image](https://github.com/metagov/daostar/assets/41290852/d40bd5c6-2865-4293-92f5-c4059aa21928)
