### ISSUE TITLE
Restore the indexed data from the history version contract

### ISSUE THREAD

**Issue by crazyyuan** [metagov/daostar#158]
- [x] Pick up the history Subgraph code used to index, and commit these to main branch.
- [x] Create a new Subgraph Service to index data.
- [x] Combine the existing data and new indexed data to show on the DAOstar website.

**Comment by Rashmi-278** [comment]
@crazyyuan Hi Kahn, is there a link to the old Subgraph indexer used before?

**Comment by crazyyuan** [comment]
> @crazyyuan Hi Kahn, is there a link to the old Subgraph indexer used before?

There is only one link, the main network Subgraph indexer is updated (new code, new contract) by Isaac. so we should create a new one. 
Is it possible to combine 2 indexer data on the front-end?

**Comment by Rashmi-278** [comment]
Me and Kahn will be working on this task, checkpoint 3, ie Combine the existing data and new indexed data to show on the DAOstar website, will be handled by me

**Comment by crazyyuan** [comment]
The new Subgraph Service for the history version contract is working.
https://thegraph.com/hosted-service/subgraph/crazyyuan/daostar-ethereum-main-v0

**Comment by thelastjosh** [comment]
Sounds like we're close to closing this today.

**Comment by Rashmi-278** [comment]
Old Smart Contracts are being indexed here: https://thegraph.com/hosted-service/subgraph/rashmi-278/daostar-ethereum-mainnet-v0

**Comment by Rashmi-278** [comment]
Errors resolved here: https://github.com/metagov/daostar/pull/172
