### ISSUE TITLE
Arbitrum Foundation Grant

### ISSUE THREAD

**Issue by amanwithwings** [metagov/daostar#169]
Milestone 1: First round of EIP-4824 adoption drive through Arbitrum. We expect to complete this milestone within 3 months from the grant date. Our goal is to have a minimum of 3 DAOs on Arbitrum achieve EIP-4824 compliance within this timeframe. 

Milestone 2: Implementation of the Regulatory Interface. We aim to complete this milestone within 6 months from the start of the project.

Milestone 3: Authoring of the DAO tax standard. We expect to release the tax standard V1.0 within 9 months from the start of the project.

**Comment by amanwithwings** [comment]
DAOs on Arbitrum: 

1. Arbitrum
2. Badger
3. Balancer
4. Curve
5. Paraswap
6. Sushi
7. Uniswap
8. 1inch
9. Across Protocol
10. Galxe
11. Aave
12. Compound
13. Silo
14. OOKI 
15. UMAMI
16. Yearn
17. MakerDAO
18. Frax
19. Lybra
20. GMX

**Comment by thelastjosh** [comment]
This has been awarded (10k USD, with 40k USD in incentive fees) but the agreement has not been signed yet. KYB complete.
