### ISSUE TITLE
Registration support Arbitrum mainnet

### ISSUE THREAD

**Issue by crazyyuan** [metagov/daostar#192]
- [x] Deploy all relevant contracts.
- [x] Create TheGraph service.
- [x] DAOstar website integration.
- [x] Document update.

**Comment by crazyyuan** [comment]
The contracts are all deployed and verified.
[EIP4824Index](https://arbiscan.io/address/0x18cbb356cd64193b1a0ca49911fc72cb3d02a5e4)
[EIP4824Registration](https://arbiscan.io/address/0x65D17d117C190f7A4cc784b56a17E3f7Edde5762)
[EIP4824RegistrationSummoner](https://arbiscan.io/address/0x5c0340ad34f7284f9272e784ff76638e8ddb5de4)

**Comment by crazyyuan** [comment]
TheGraph Indexer has been deployed on the Arbitrum network.
https://thegraph.com/hosted-service/subgraph/crazyyuan/daostar-arbitrum

PR for these: [#194](https://github.com/metagov/daostar/pull/194)

**Comment by Rashmi-278** [comment]
Done https://github.com/metagov/daostar/pull/195

**Comment by Rashmi-278** [comment]
Changes are live

**Comment by Rashmi-278** [comment]
Ready to close after merging #194
