### ISSUE TITLE
daoURI for Lodestar DAO

### ISSUE THREAD

**Issue by amanwithwings** [metagov/daostar#199]
Lodestar Finance recently voted to adopt EIP-4824: https://snapshot.org/#/lodestarfinance.eth/proposal/0x38ffe468e5da476833074ed0b3496efa00d52a5424b70d5a088790bf7a052f6d 

We need to build their daoURI so that they can adopt the standard. 

Blockers: 
1. They are not in Boardroom. How do we build their membersURI?
2. They want to include a few contracts in the contractsRegistry.

**Comment by Rashmi-278** [comment]
@amanwithwings 

Here's the members URI JSON for Lodestar Finance

https://gist.github.com/Rashmi-278/19d93da7b9fce94e6a874e10e30b2242

Please share this with their team
They should be hosting this JSON file

Here's data to generate a DAO URI for Lodestar Finance Snapshot Governance on Arbitrum

**Name:** Lodestar Finance
**Description:** Lodestar Finance is an algorithmic borrowing and lending protocol that aims to bring the critical DeFi primitive of decentralized money markets to Arbitrum communities.

**Members URI:** https://gist.github.com/Rashmi-278/19d93da7b9fce94e6a874e10e30b2242

Activity Log URI: https://snapshot.org/#/lodestarfinance.eth
Proposals URI: https://services.daostar.org/api/v1/snapshot/proposals/lodestarfinance.eth

Governance URI: https://snapshot.org/#/lodestarfinance.eth

Issuers URI: https://odestarfinance.io/

Contracts Registry URI: https://docs.lodestarfinance.io/getting-started/deployed-contracts

**Comment by amanwithwings** [comment]
Thanks for the quick turnaround on this, @Rashmi-278. A question - is the membersURI static? It wouldn't be as useful if it is- we need the URI to return an up-to-date list of their members.

**Comment by Rashmi-278** [comment]
> Thanks for the quick turnaround on this, @Rashmi-278. A question - is the membersURI static? It wouldn't be as useful if it is- we need the URI to return an up-to-date list of their members.

Hey Aman, good catch, yes I can give a dynamic link, I have a python script I used for this, let me host an endpoint

**Comment by Rashmi-278** [comment]
![image](https://github.com/metagov/daostar/assets/41290852/9bebe061-81f2-42ec-9a7f-2e77d0ea2952)
__

**Comment by thelastjosh** [comment]
It should be "@context": "http://www.daostar.org/schemas" above

**Comment by thelastjosh** [comment]
Just noting here that this is high priority because it is part of the Arbitrum grant #184

**Comment by Rashmi-278** [comment]
Lodestar Registration Successful!
![image](https://github.com/metagov/daostar/assets/41290852/e766fd79-527f-482c-ac88-033ef2d82eb8)

LInk: https://daostar.org/registration/arbitrum:0x378585249fd40c4736b88e577a0110e9fe491e3f
