### ISSUE TITLE
Integrate Snapshot's daoURI with the attestation framework

### ISSUE THREAD

**Issue by Rashmi-278** [metagov/daostar#205]
Display the DAO URI of snapshot spaces, published by snapshot https://hub.snapshot.org/api/eip4824/<space_name>
on our frontend with disclaimer that the data provided is by Snapshot and NOT by DAO themselves

**Comment by crazyyuan** [comment]
It seems that the 'membersURI' from the Snapshot eip4824 API just contains space members, which are not voters. 
This is not what we want.

**Comment by thelastjosh** [comment]
What we need to do here next is clearly describe what it means to publish daoURI data through an attestation, since Snapshot will be publishing daoURI data about DAOs through an attestation.

**Comment by Rashmi-278** [comment]
Created a PR on Snapshot to include voters in their membersURI
https://github.com/snapshot-labs/snapshot-hub/pull/812

Conveyed this to their team, waiting for their review and response on this

**Comment by Rashmi-278** [comment]
Fabien review,

> In some space there can be millions of voters, I think we need to put a limit on the query otherwise it will take too long to resolve or load for an integrator

Based on this, I've added limit, pagination, and uniqueness checks for members.
I've pushed my changes fo further review.

**Comment by Rashmi-278** [comment]
Pushed changes, https://github.com/snapshot-labs/snapshot-hub/pull/812

**Comment by thelastjosh** [comment]
Just taking a long time, ball is still in their court to review Rashmi's PR.

**Comment by thelastjosh** [comment]
This was combined with #239 , will close for now.
