### ISSUE TITLE
Migrate TheGraph from hosted service to subgraph studio

### ISSUE THREAD

**Issue by crazyyuan** [metagov/daostar#208]
The hosted service will begin sunsetting. Developers are encouraged to [upgrade their subgraphs to The Graph Network](https://thegraph.com/docs/en/cookbook/upgrading-a-subgraph/) as more networks are supported.
https://thegraph.com/blog/sunsetting-hosted-service/

**Comment by Rashmi-278** [comment]
Hosted service subgraph endpoints will be deprecated on June 12th, 2024 (the cutoff date).

https://youtu.be/hCmX5Dlhdjw

**Comment by Rashmi-278** [comment]
Updated

DAOstar-gnosis : https://thegraph.com/hosted-service/subgraph/rashmi-278/daostar-gnosis
DAOstar-optmisim: https://thegraph.com/hosted-service/subgraph/rashmi-278/daostar-optimism
DAOstar-bnb-bruno: https://thegraph.com/hosted-service/subgraph/rashmi-278/daostar-bnb-bruno

Owner address for these is one of my wallet address, 0x86b9eA8f3fb705fCFAfbAD59D48A869d79972eeF

In future, we plan to move it to DAOstar DAO owned address to fund for API costs with GRT tokens

**Comment by Rashmi-278** [comment]
Code upgrade PR to pull IPFS determinstically: https://github.com/metagov/daostar/pull/237

Recent:  [ Need some ETH to publish these]
https://thegraph.com/studio/subgraph/daostar-arbitrum-one/  
https://thegraph.com/studio/subgraph/daostar-mainnet

**Comment by Rashmi-278** [comment]
**To-Do:**
- Address errors for unsupported networks:
  - DAOstar on Optimism Goerli
  - DAOstar on Arbitrum Goerli
- Update Frontend with new API links

**Comment by Rashmi-278** [comment]
We have already updated the subgraph endpoints for the active chains, and all /latest versions have been updated accordingly. Here are the current endpoints we are using:

`endpoints: {
    mainnet: `https://api.studio.thegraph.com/query/74263/daostar-mainnet/version/latest`,
    gnosis: `https://api.studio.thegraph.com/query/74263/daostar-gnosis/version/latest`,
    chapel: `https://api.studio.thegraph.com/query/74263/daostar-bnb-bruno/version/latest`, //bnb-bruno
    optimism: `https://api.studio.thegraph.com/query/74263/daostar-optimism/version/latest`,
    arbitrum: `https://api.studio.thegraph.com/query/74263/daostar-arbitrum-one/version/latest`
}
`
Closing this issue for now.
