### ISSUE TITLE
Minor front-end improvements

### ISSUE THREAD

**Issue by amanwithwings** [metagov/daostar#214]
<img width="1459" alt="Screenshot 2024-03-21 at 4 22 43 PM" src="https://github.com/metagov/daostar/assets/68982632/5cc6bdbb-c001-44d2-981a-036036cb4da4">

1. Wondering if instead of _"contract address"_ we should use _"contract owner"_ as that sounds more appropriate. 
2. I don't see the address of the registration contract. Feels like that should be included somewhere?

Also, we have a duplicate registration from Lodestar currently displayed by the explore page. It needs to be removed.

**Comment by Rashmi-278** [comment]
@amanwithwings 
1. "Contract Owner" or "Registered By" both sound appropriate to me. I agree that we should change the name. 
2. Registration Contract right now is in the link of Registration. I'm adding this to the display too.

**Comment by Rashmi-278** [comment]
![image](https://github.com/metagov/daostar/assets/41290852/ae22bf92-0015-4f32-9e41-76660fc98887)

**Comment by Rashmi-278** [comment]
Hours worked: 1
Along with other minor UI fixes that were mentioned in telgram group  from feedback and meeting discussion
