### ISSUE TITLE
Update ENS Subgraph URL

### ISSUE THREAD

**Issue by gskril** [metagov/daostar#236]
The ENS subgraph URL used in this repo (`https://api.thegraph.com/subgraphs/name/ensdomains/ens`) will have a global rate limit added on June 12. To avoid this, it is recommended to create your own API key with TheGraph.

It’s free for the first 100k requests/month, and the ENS DAO Ecosystem Working Group is offering potential sponsorships if you go beyond that. [Here is a video](https://www.loom.com/share/a03ca8bc85624134bc7344a199200f0b) walking through the setup process (less than 5 mins).

This is due to [TheGraph sunsetting its hosted service](https://thegraph.com/docs/en/sunrise/). The old URL will begin serving requests from an ENS DAO-sponsored API key, so **this is not a breaking change** for ENS, but it will introduce a more restrictive rate limit.

---

Where the hosted subgraph is used: https://github.com/metagov/daostar/blob/main/daostar-website/src/index.js#L43

**Comment by thelastjosh** [comment]
@Rashmi-278 will let you review and close as appropriate!

**Comment by Rashmi-278** [comment]
@gskril 
Thank you for the heads up regarding the global rate limit on the ENS Subgraph URL

However, our usage currently stays well below 10k requests per month, so the new rate limit should not affect our operations. We will monitor our request count closely and consider setting up our API key with TheGraph if our needs change.

We appreciate you for letting us know! Closing this issue for now.
