### ISSUE TITLE
Create first draft of docs for exploring the reference implementations and for api.daostar.org

### ISSUE THREAD

**Issue by thelastjosh** [metagov/daostar#28]
Create a series of readme files or a readthedocs or a gitbook or something linkable and hosted on this GitHub for docs.

What are we really trying to do with these docs? Enhance adoption on (1) DAO tooling companies (think members of DAOstar) and to a lesser extent (2) DAOs, especially more sophisticated DAOs who are building their own infrastructure. Normal DAOs will be interacting with the app frontend.

1. We're trying to incentivize people to create their own reference implementations / upgrade their own DAOs according the DAOstar.
2. To do that, we need to clean up our repository of reference implementations, and give people access to them via a good set of docs.

initial sections might be:
1. List of factory contracts and where they are
2. Existing reference implementations
3. Api.daostar.org

This should be super clean and simple, since our infra is very lightweight!

**Comment by thelastjosh** [comment]
Note, Luke mentioned we already have swagger set up at https://daostar.org/api/docs/#/

**Comment by lukvmil** [comment]
Super lean version live at http://daostar.readthedocs.io/, all files are located in the docs subdirectory of this repo, please modify and expand!

**Comment by editorai** [comment]
Is there any place we can find the list of factory contracts now?

**Comment by thelastjosh** [comment]
> Is there any place we can find the list of factory contracts now?

@ipatka I can't find this in our current docs (in either Luke's docs or yours), I think you posted it a Telegram chat a while back?
