### ISSUE TITLE
Publish attestations in explore and/or management interface

### ISSUE THREAD

**Issue by thelastjosh** [metagov/daostar#45]
Display the (off-chain) attestations via the Attestations for DAOs standard being published by Govrn in the DAOstar frontend. On request of Aaron of Govrn.

**Comment by thelastjosh** [comment]
This is going to be tackled as part of the REPUTABLE <> DAOstar project, by Mendes.

**Comment by Rashmi-278** [comment]
Needs a status update. I think this issue was worked on and completed.
