### ISSUE TITLE
Fix design of daoURI registration & management flow

### ISSUE THREAD

**Issue by thelastjosh** [metagov/daostar#75]
Right now, we can't even access the management flow for daoURI.

Before connecting wallet, I want to be able to:
1. Deploy a registration with a daoURI, with or without a manager address
2. See and explore existing registrations and daoURIs, EVEN IF THEY HAVE NOT BEEN "CLAIMED" BY A DAO
3. (maybe, needs further design thinking) manage orphaned registrations that neither have a manager address NOR have been claimed by a DAO

After connecting my wallet, I want to be able to:
1. See all the DAOs for which I am a manager
4. Edit the daoURI for those DAOs by connecting and interacting with the DAO's registration contract
5. Query the existing URIs published in daoURI
6. (eventually) modify the URIs published in daoURI, especially if they are hosted by DAOstar itself

**Comment by thelastjosh** [comment]
Next step here is to evaluate current codebase with Tucker @TuckerMcLachlan  (and maybe Isaac @ipatka ) next Friday.

**Comment by thelastjosh** [comment]
Note specific issue with managers: https://github.com/metagov/daostar/issues/126

`Deploy a registration with a daoURI, with or without a manager address`
DONE

`See and explore existing registrations and daoURIs, EVEN IF THEY HAVE NOT BEEN "CLAIMED" BY A DAO`
NOT done

None of the other things are done.

This issue we may address in a daostar.org design + technical workshop to address together all these issues.

**Comment by thelastjosh** [comment]
Rashmi will set up + schedule a 2-hour workshop call in early September to go over and consolidate outstanding design issues. Before doing so she will finish consolidating all the design issues into a second document.

**Comment by Rashmi-278** [comment]
All the listed issues in this have been moved [DAOstar improvements spec](https://docs.google.com/document/d/1Egl9MXYNJFaXev1o6rdVFTZ-QNuCrJyTNkeJ2Qof6jY)
