### ISSUE TITLE
Support PlanckerDAO in completing and publishing the NFT Voting Standard as DAOIP#?

### ISSUE THREAD

**Issue by unfriendlyamendment** [metagov/daostar#76]
1. Document: [Notion Document](https://plancker.notion.site/Daostar-implementation-for-Nouns-02ed418eccc841dc9fe94e6f904c02f1)
2. Does PlanckerDAO want to lead a DAO* WG? If so, who else in the WG?

**Comment by thelastjosh** [comment]
Alternate possibility or in addition: support / hire someone in the CN ecosystem to build ANY standard! As long as it's supported by a range of entities in Asia. The hire should cat-herd people to help the ecosystem actually execute.

**Comment by 0xPabloLI** [comment]
Found some bugs while implementing for Nouns: https://discourse.nouns.wtf/t/bug-report-for-nouns-subgraph-and-nouns-agora/4758

**Comment by amanwithwings** [comment]
Are we still working on this, @unfriendlyamendment? If not, we can close/consolidate it to other open issues.

**Comment by 0xPabloLI** [comment]
> Are we still working on this, @unfriendlyamendment? If not, we can close/consolidate it to other open issues.

Yes, I think close it for now.
