### ISSUE TITLE
Create JD for "community & vibes person" 

### ISSUE THREAD

**Issue by thelastjosh** [metagov/daostar#98]
Ideally Asia-based, as we re-center toward Asia.

- can curate Asia vibes
- has a "good sense of smell" in Asia, especially China, Japan, South Korea, Singapore
- curating the general community vibes, including current DAOstar membership (so good English required!)
- engage communities
- help run/moderate the main roundtable
- socialize standards
- research, e.g. marketing survey
- curating events for DAOs & standards in Asia
- communicating the vision of DAOstar
- coordinating the team around the Asia vision
- apply for grants in Asia
- depending on grant availability, building out and leading a small team in Asia

**Comment by thelastjosh** [comment]
Afterwards, post it on the daostar.one Notion and the metagov.org/join/ site!

**Comment by thelastjosh** [comment]
Here's the prompt I gave GPT: 

# Prompt
Write a job description for a community lead for DAOstar, the standards body for DAOs, that matches both our global profile as well as our current pivot toward Asia. The job description has the following requirements:

- curating the general community vibes, including the current DAOstar membership which is mostly based in the USA and Europe (so excellent English is required!)
- curating small, high-quality events for DAOs & standards in Asia
- apply for grants and sponsorships in Asia, especially in connection with such events
- help run/moderate the main monthly roundtable
- help run/moderate the Asia monthly roundtable
- socialize standards in the DAO community
- communicating the vision of DAOs, DAO infrastructure, and DAOstar
- should be based in Asia and can curate Asia vibes
- has a "good sense of smell" in Asia, especially China, Japan, South Korea, Singapore
- occasionally lead research projects, e.g. marketing surveys
- depending on grant availability, building out and leading a small team in Asia

# Output
Job Title: Global and Asia Community Lead - DAOstar

Location: Asia (Preferably China, Japan, South Korea, or Singapore)

About DAOstar:

DAOstar is a leading global standards body for decentralized autonomous organizations (DAOs). Our mission is to set the standards and pave the way for the future of DAOs and DAO infrastructure. As we pivot our focus towards Asia, we are seeking a highly-skilled Global and Asia Community Lead to foster our community engagement, curate high-quality events, and represent our vision in the region.

Key Responsibilities:

Community Engagement and Curation: Curate the general community vibe of DAOstar, including current membership predominantly based in the USA and Europe. Build, manage, and drive engagement strategies within the DAOstar community.

Event Planning: Organize and curate high-quality, small-scale events for DAOs and standards in Asia. This includes venue selection, coordination with local partners, event publicity, and ensuring an impactful, memorable event experience.

Grant and Sponsorship Applications: Apply for relevant grants and sponsorships in Asia, particularly in association with events. Manage all stages of the application process and provide progress reports on the use of obtained funds.

Roundtable Moderation: Assist in running and moderating both the main monthly DAOstar roundtable and the Asia monthly roundtable. Promote rich, meaningful discourse and engagement.

Standards Socialization: Advocate for DAOstar's standards within the global and Asian DAO communities. Provide education and guidance on our initiatives, best practices, and value propositions.

Communication: Articulate the vision of DAOs, DAO infrastructure, and DAOstar to a global audience, with particular emphasis on the Asian community. This includes public speaking, content creation, and acting as the spokesperson for DAOstar.

Market Research: Occasionally lead research projects such as marketing surveys to gather insights on market trends, potential opportunities, and challenges within the Asian DAO space.

Team Leadership: Depending on grant availability, lead and develop a small team in Asia to further DAOstar's initiatives in the region.

Qualifications:

Fluent in English and at least one Asian language.
Prior experience in community management, preferably within the blockchain/tech industry.
Proven track record in organizing events and securing grants/sponsorships.
Exceptional interpersonal and communication skills.
Strong understanding and network within the Asian market, particularly in China, Japan, South Korea, and Singapore.
Familiarity with market research methodologies and analysis.
Leadership experience, especially in building and leading teams.
Traits:

A "good sense of smell" - an ability to identify trends, opportunities, and potential issues within the Asian market.
A passion for DAOs and blockchain technology.
Ability to work autonomously and demonstrate creativity and strategic thinking.
Strong problem-solving skills.
If you are driven by the potential of blockchain technology and DAOs and relish the challenge of growing our community engagement and footprint in Asia, we'd love to hear from you. DAOstar is committed to diversity and equal opportunities in our organization.

**Comment by unfriendlyamendment** [comment]
Updated

Community Lead - DAOstar

Location: Asia (Preferably Mainland China, Hong Kong, Japan, South Korea, Singapore, Taiwan)
Status: Part-time and remote 

About DAOstar
DAOstar is the global standards body for decentralized autonomous organizations (DAOs). Our mission is to build standards and infrastructure for DAOs and DAO tooling. 

As we expand our global purview with the goal of connecting with DAO builders and operators across Asia, we are seeking a highly-skilled Community Lead with deep experience in the region to foster our community engagement, curate high-quality events, and represent our vision both globally and within the region.

Qualifications
We are looking for someone located in Asia, and willing to travel and be present in DAO gatherings and communities, as appropriate. 
Fluent in English and at least one East Asian language, especially Mandarin, Japanese, or Korean.
Prior experience in community management, preferably within the DAO or blockchain industry or tech more broadly.
Proven track record in organizing events and preferably experience securing grants/sponsorships.
Exceptional interpersonal and communication skills.
Strong understanding and network within the DAO and public goods ecosystem in Asia. Additional understanding and network within India and Southeast Asia is welcome though not required.
Familiarity with market research methodologies and analysis.
Ability to coordinate amongst many stakeholders across time zones. 

Traits
An ability to identify trends, opportunities, and potential issues within the Asian market - someone who has their pulse on what’s happening as they live and breathe the DAO space in Asia.
A passion for decentralized forms of coordination amongst / across communities.
Ability to work autonomously and demonstrate creativity and strategic thinking, while also enjoying working in a global team.
Strong problem-solving skills.
If you are driven by the potential of blockchain technology and DAOs and relish the challenge of growing the DAO ecosystem in Asia, we'd love to hear from you.

Key Responsibilities
Community Engagement and Curation: Curate the general community vibe of DAOstar, coordinating with the other global community leads. Build, manage, and drive engagement strategies within the DAOstar community, specifically focused in Asia. 

Event Planning: Organize and curate high-quality, small-scale events for DAOs and standards in Asia. This includes running workshops, selecting venues, coordinating with local partners, publicizing events, and ensuring an impactful, memorable event experience.

Grant and Sponsorship Applications: Apply for relevant grants and sponsorships in Asia, particularly in association with events. Manage all stages of the application process and provide progress reports on the use of obtained funds. Coordinate with and support the global DAOstar team on grant opportunities, as needed. 

Roundtable Moderation: Assist in running and moderating the Asia monthly roundtable. Promote rich, meaningful discourse and engagement.

Standards Socialization: Advocate for DAOstar's standards within the global and Asian DAO communities, as appropriate. Provide education and guidance on our initiatives, best practices, and value propositions.

Communication: Articulate the vision of DAOs, DAO infrastructure, and DAOstar to a global audience, with particular emphasis on the Asian community. This includes public speaking, content creation, and acting as the spokesperson for DAOstar.

Market Research: Occasionally lead research projects such as marketing surveys to gather insights on market trends, potential opportunities, and challenges within the Asian DAO space. As an example, see [Open Problems in DAOs](https://docs.google.com/document/d/1LvqvarU951r9dHMif4dhXanmkq_eQ_k5xTZC5-t7lkM/edit#heading=h.d9b7hkj3ezl6) https://daoscience.org/. 

Team Leadership: Depending on grant availability, lead and develop a small team in Asia to further DAOstar's initiatives in the region.
