### ISSUE TITLE
Optimism Grant 1 : EIP-4824

### ISSUE THREAD

**Issue by amanwithwings** [metagov/daostar#99]
The successful implementation and deployment of the EIP-4824 standard in the Optimism ecosystem, confirmed by Optimism and at least three other large DAOs on Optimism publishing a daoURI. 

Tasks: 
1. Build the end-points for Optimism DAO + 3 other DAOs on Optimism (if these are Snapshot DAOs, we can just use the Snapshot integration). 
2. Get the proposal through the governance of all 4 DAOs and get them to publish a daoURI. 

**Due date: end of September 2023**

**The grant will only be received once the aforementioned tasks have been completed.**

Original proposal: https://gov.optimism.io/t/final-daostar-governance-standards-for-the-optimism-ecosystem/6181

**Comment by amanwithwings** [comment]
DAOs on Optimism (from Snapshot): 

Has governance on Optimism: 

1. Optimism Collective: https://www.optimism.io/  |  https://snapshot.org/#/opcollective.eth
2. dHedge DAO: https://www.dhedge.org/  |   https://snapshot.org/#/gov.dhedge.eth
3.  Bored Town: https://twitter.com/boredtownnft   |    https://snapshot.org/#/boredtown.eth   
4. Sonne Finance: https://sonne.finance/   |   https://snapshot.org/#/sonnefi.eth
5. Thales: https://thalesmarket.io/   |   https://snapshot.org/#/thalescouncil.eth


Has voters on Optimism:

1. Stargate: https://stargate.finance/  |  https://snapshot.org/#/stgdao.eth
2. Perpetual Protocol: https://perp.com/  |  https://snapshot.org/#/vote-perp.eth
3. Popcorn: https://pop.network/  |  https://snapshot.org/#/popcorn-snapshot.eth
4. SyncSwap: https://syncswap.xyz/  |  https://snapshot.org/#/syncswapxyz.eth 
5. Reunit DAO: https://everywhere.finance/  |   https://snapshot.org/#/reunitdao.eth
6. NFTEarth: https://nftearth.exchange/   |   https://snapshot.org/#/nftearthl2.eth
7. Lyra Finance: https://www.lyra.finance/    |  https://snapshot.org/#/lyra.eth
8. Premia: https://premia.finance/   |   https://snapshot.org/#/premia.eth

**Comment by amanwithwings** [comment]
Proposal to Perpetual Protocol: https://gov.perp.fi/t/extend-perpetual-protocol-dao-with-eip-4824/999

**Comment by eleventh19** [comment]
Deadline is coming up (Sept 20). Have 2 DAOs that might adopt 4824 - OPT Collective and ShapeShift. Blocker: need to construct the DAO URI for this. Have most of it aside from members URI. 

Still searching for 2 more DAOs, as the benchmark was OPT Collective + 3 DAOs. Tried getting discussion going in DAO specific platforms. Hoping that OPT Collective and ShapeShift get it done in the next few days to help move the needle for other orgs. 

Going to connect with Alex @ CharmVerse to try and get other leads on potential DAOs. Will follow up with LXDAO to see if they might be able to publish the URI. 

We need more direct contacts vs just posting publicly given the timelines.

**Comment by thelastjosh** [comment]
@amanwithwings posted updated already, presentation happening tomorrow (Aman will be taking it), plus someone at Optimism reached out to me to actually pay us. (we just finally completed their KYB).

**Comment by amanwithwings** [comment]
Update to Optimism: https://gov.optimism.io/t/final-daostar-governance-standards-for-the-optimism-ecosystem/6181/36

**Comment by thelastjosh** [comment]
Sounds like easiest is to deploy this on EAS, it will be just a transaction on EAS.

**Comment by thelastjosh** [comment]
Noting that the main blocker to resolving this issue is #170

**Comment by Rashmi-278** [comment]
Unlock DAO, Shapeshift DAO adopted DAO URI

We have positive response from Stargate Finance and InstaDapp, maybe we could reconnect ?

**Comment by xiaohou77** [comment]
Option 1:
1. **User entry**: https://optimism.easscan.org/, make an attestation about DAO name and URI
2. **Allow list managed by DAO***: Grant Josh/Aman as admins, admin can grant OP foundation (ENS or EOA wallet) as member who can make an attestation onchain, admin can also make an attestation onchain
3. **DAO name and URL**: data stored on chain (Schema #xxx)
4. Deploy schema and resolver contract on OP Seplia and OP mainnet
5. Hours of development: around 5 hours
<img width="1143" alt="image" src="https://github.com/metagov/daostar/assets/38149053/c49124a5-1845-492b-a82e-d348a4e78802">

Option 2 (only list the differences):
1. **User entry**: Build it in DAOstar.org Register frontend, see screenshot as below,
 - Integrate EAS SDK, connect wallet, attest DAO URI after registered via DAO* contract
2. +Deploy new frontend
3. Hours of development: around 8 hours

<img width="1067" alt="image" src="https://github.com/metagov/daostar/assets/38149053/4d5ddb96-f495-42bd-b1dd-0e394b216d3b">

**Comment by amanwithwings** [comment]
Thanks for the quick turnaround, @xiaohou77! Since they roughly take the same time, I think we can go with the front-end. It incorporates extra functionality to the website and if people want to use EAS's front-end, they can do that as well.

We need to make sure any UI change fits our design language. And just to note, I would personally prefer a toggle button like this,: 
<img width="1459" alt="Screenshot 2024-03-19 at 5 41 02 PM" src="https://github.com/metagov/daostar/assets/68982632/c6aafabf-cdbb-49ce-9fc3-6fb4700b00bd">
